name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  go:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: install golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'

    - name: test and generate coverage.txt
      run: make coverage

    - name: format
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
        
    - name: upload coverage reports to codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: typovrak/typotestcolor
